if (!OMSystem.OrkutManager.Language)
    OMSystem.OrkutManager.Language = {};

OMSystem.OrkutManager.Language = {
    Get: function()
    {
        var Language = {};
        var config_lang = OMSystem.OrkutManager.PrefManager.Get("Language", "pt-BR");
        if (config_lang == "pt-BR") {
            Language =
                    {
                        AddRelated: "Adicionar relacionada",
                        AddRelatedInsertId: "Insira o ID da comunidade que deseja relacionar",
                        AcceptAll: "Aceitar todos",
                        Bookmarks: "Favoritos",
                        BookmarksT: "Fav. Topicos",
                        ChatSetAs: "Marcar como chat",
                        ChatUnsetAs: "Remover chat",
                        Colors: "Cores",
                        Config: "Configura%E7%E3o",
                        DateTimeDays: new Array("Domingo", "Segunda-Feira", "Ter%E7a-Feira", "Quarta-Feira", "Quinta-Feira", "Sexta-Feira", "S%E1bado"),
                        DateTimeMonths: new Array("Janeiro", "Fevereiro", "Mar%E7o", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"),
                        DenyAll: "Recusar todos",
                        Fonts: "Fontes",
                        Forum: "F%F3rum",
                        Home: "In%EDcio",
                        Last: "%DAltima",
                        ModConfirm: "Registrar no log da modera%E7%E3o?",
                        ModDeletePoll: "Deletar enquete?",
                        ModDeleteTopic: "Deletar t%F3pico?",
                        ModDo: "Mod",
                        ModSetAs: "Marcar como mod",
                        ModUnsetAs: "Desmarcar mod",
                        PendingMember: "Pendentes",
                        Profile: "Perfil",
                        QReply: "QResp",
                        Quote: "Quote",
                        QuoteMarked: "Quoting",
                        Refresh: "Recarregar",
                        Reply: "Responder",
                        Save: "Salvar",
                        Scrapbook: "P%E1gina de recados",
                        ScrapCount: "Voc%EA tem $COUNT$ novos scraps. <a href='/Scrapbook'>Scrapbook</a><br />$USER$ escreveu:<br /> $TEXT$",
                        ShowHide: "Mostrar/esconder",
                        SpoilerText: "<b>Aviso:</b> Esta &aacute;rea cont&eacute;m <b>revela&ccedil;&otilde;es sobre o enredo</b> (<i><span style=\\'color: red\\'>spoilers</span></i>).",
                        Start: "Iniciar",
                        Stop: "Parar",
                        ToolbarAlignCenter: "Alinhar: Centro",
                        ToolbarAlignJustify: "Alinhar: Justificado",
                        ToolbarAlignLeft: "Alinhar: Esquerda",
                        ToolbarAlignRight: "Alinhar: Direita",
                        ToolbarBlink: "Blink",
                        ToolbarBold: "Negrito",
                        ToolbarCollapse: "Collapse",
                        ToolbarColorPicker: "Colorpicker",
                        ToolbarDecrypt: "Decifrar",
                        ToolbarEmoticons: "Emoticons",
                        ToolbarEncrypt: "Cifrar",
                        ToolbarFont: "Fonte",
                        ToolbarFontG: "Fonte maior",
                        ToolbarFontS: "Fonte menor",
                        ToolbarFontSize: "Tamanho da fonte",
                        ToolbarImage: "Imagem",
                        ToolbarItalic: "Italico",
                        ToolbarLink: "Link",
                        ToolbarMaskLinks: "Mascarar links",
                        ToolbarNewLine: "Nova linha",
                        ToolbarQuote: "Quotemark",
                        ToolbarSource: "Source",
                        ToolbarSpoiler: "Spoiler",
                        ToolbarStrike: "Strike",
                        ToolbarTime: "Hora/Data",
                        ToolbarUnderline: "Sublinhado",
                        Topic: "T%F3pico",
                        UnjoinConfirm: "Sair da comunidade?",
                        UnjoinSelected: "Sair das selecionadas",
                        Update: "Atualizar",
                        ViewAll: "Ver todos",
                        Back: "Voltar",
                        Sending: "Enviando",
                        adversiment: "Publicidade",
                        MarkNotify: "Receber avisos",
                        UnMarkNotify: "Cancelar avisos",
                        loginAgain: "Aparentemente você está deslogado do orkut, deseja logar-se?",
                        MassdelTopics: "Deletar posts selecionados",
                        MassdelTopicsConfirm: "Deseja deletar os posts selecionados?",
                        MassUnjoinCmmWarn: "Obs.: Sair de mais de 50 comunidades ao mesmo tempo pode fazer sua conta entrar no filtro. Aguarde ao menos 5 minutos para sair novamente.",
                        EnablePreviewTopic: "Ativar Preview",
                        DisablePreviewTopic: "Desativar Preview",
                        title: "Titulo",
                        noMessage: "Campo mensagem vazio",
                        subject: "Assunto",
                        ViewMessage: "Ver %BB ",
                        errorSendindMsg: 'O Orkut apresentou um erro ao enviar esta mensagem. Verifique ela abaixo',
                        unjoinBind: 'Aguarde, você já clicou em sair, espere o processo terminar.',
                        unjoiningMsg: 'Saindo, aguarde por favor ...',
                        deleteAllPolls: "Deletar selecionadas",
                        deletingAllPolls: "Aguarde, deletando ..."

                    }
        } else if (config_lang == "en-US") {
            Language =
                    {
                        AddRelated: "Add related",
                        AddRelatedInsertId: "Insert community ID to relate",
                        AcceptAll: "Accept all",
                        Bookmarks: "Bookmarks",
                        BookmarksT: "BkTopics",
                        ChatSetAs: "Set as chat",
                        ChatUnsetAs: "Unset chat",
                        Colors: "Colors",
                        Config: "Config",
                        DateTimeDays: new Array("Sunday", "Monday", "Thuesday", "Wednesday", "Thursday", "Friday", "Saturday"),
                        DateTimeMonths: new Array("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"),
                        DenyAll: "Deny all",
                        Fonts: "Fonts",
                        Forum: "Forum",
                        Home: "Home",
                        Last: "Last",
                        ModConfirm: "Register in mod log?",
                        ModDeletePoll: "Delete poll?",
                        ModDeleteTopic: "Delete topic?",
                        ModDo: "Mod",
                        ModSetAs: "Set as mod",
                        ModUnsetAs: "Unset mod",
                        PendingMember: "Pending",
                        Profile: "Profile",
                        QReply: "QReply",
                        Quote: "Quote",
                        QuoteMarked: "Quoting",
                        Refresh: "Refresh",
                        Reply: "Reply",
                        Save: "Save",
                        Scrapbook: "Scrapbook",
                        ScrapCount: "You have $COUNT$ new scraps. <a href='/Scrapbook'>Go to scrapbook page</a><br />$USER$ wrote:<br /> $TEXT$",
                        ShowHide: "Show/Hide",
                        SpoilerText: "<b>Warning:</b> This area contains <b>revelations about the plot</b> (<i><span style=\\'color: red\\'>spoilers</span></i>).",
                        Start: "Start",
                        Stop: "Stop",
                        ToolbarAlignCenter: "Align: Center",
                        ToolbarAlignJustify: "Align: Justify",
                        ToolbarAlignLeft: "Align: Left",
                        ToolbarAlignRight: "Align: Right",
                        ToolbarBlink: "Blink",
                        ToolbarBold: "Bold",
                        ToolbarCollapse: "Collapse",
                        ToolbarColorPicker: "Colorpicker",
                        ToolbarDecrypt: "Decrypt",
                        ToolbarEmoticons: "Emoticons",
                        ToolbarEncrypt: "Encrypt",
                        ToolbarFont: "Font",
                        ToolbarFontG: "Font Grow",
                        ToolbarFontS: "Font Shrink",
                        ToolbarFontSize: "Font Size",
                        ToolbarImage: "Image",
                        ToolbarItalic: "Italic",
                        ToolbarLink: "Link",
                        ToolbarMaskLinks: "Mask links",
                        ToolbarNewLine: "New line",
                        ToolbarQuote: "Quotemark",
                        ToolbarSource: "Source",
                        ToolbarSpoiler: "Spoiler",
                        ToolbarStrike: "Strike",
                        ToolbarTime: "DateTime",
                        ToolbarUnderline: "Underline",
                        Topic: "Topic", /* Requires escape() */
                        UnjoinConfirm: "Unjoin community?",
                        UnjoinSelected: "Unjoin Selected",
                        Update: "Update",
                        ViewAll: "View all",
                        Back: "Back",
                        Sending: "Sending",
                        adversiment: "Advertisement",
                        MarkNotify: "Receive warnings",
                        UnMarkNotify: "Cancel warnings",
                        loginAgain: "Looks like you're not logged in. Do you want loggin?",
                        MassdelTopics: "Delete selected posts",
                        MassdelTopicsConfirm: "Delete selected posts?",
                        MassUnjoinCmmWarn: "Obs.: You tried to unjoin more than 50 communities. To avoid a Orkut filter on your account, mass unjoin will be limited. Wait at least 5 minutes to try again.",
                        EnablePreviewTopic: "Enable Preview",
                        DisablePreviewTopic: "Disable Preview",
                        title: "Title",
                        noMessage: "Message field is empty",
                        subject: "Subject",
                        ViewMessage: "View scrap %BB ",
                        errorSendindMsg: 'An error ocurred while trying to send the message. Check the box below with the error.',
                        unjoinBind: "Don't click twice in the button, wait for finish!",
                        unjoiningMsg: 'Please, wait ...',
                        deleteAllPolls: "Delete selected",
                        deletingAllPolls: "Wait.. Deleting"
                    }
        }
        return Language;
    }
};